"""Authenticated artifact proxy for ``/pics`` and ``/results``.

Nginx used to proxy these paths directly to SeaweedFS, which made every
uploaded screenshot, trace, and report publicly readable to anyone who knew
the URL. This router keeps the public URL shape but gates access with either:

* a normal access token (Authorization, cookie, or ``?access_token=``), or
* a scoped short-lived ``?artifact_token=`` generated by report APIs.
"""
from __future__ import annotations

import mimetypes
from typing import Literal

import jwt as pyjwt
from fastapi import APIRouter, HTTPException, Request, Response
from fastapi.responses import Response as FastAPIResponse

from app.auth.revocation import is_revoked
from app.auth.security import JWT_ALGORITHM, JWT_SECRET, decode_token
from app.services.storage_service import fetch_bytes

router = APIRouter()

Bucket = Literal["pic", "results"]


def _cors_headers() -> dict[str, str]:
    # Trace Viewer runs on a different origin and fetches the trace URL itself.
    # The artifact token is scoped to one object, so wildcard read CORS is OK.
    return {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "GET, HEAD, OPTIONS",
        "Access-Control-Allow-Headers": "Range, If-Range, Authorization, Content-Type",
        "Access-Control-Expose-Headers": "Content-Length, Content-Range, Accept-Ranges",
        "Cache-Control": "private, max-age=300",
        "Accept-Ranges": "bytes",
    }


def _safe_key(key: str) -> str:
    if not key or key.startswith("/") or "\\" in key or ".." in key.split("/"):
        raise HTTPException(400, "Invalid artifact path")
    return key


def _extract_access_token(request: Request) -> str | None:
    auth = request.headers.get("authorization") or request.headers.get("Authorization")
    if auth and auth.lower().startswith("bearer "):
        return auth.split(" ", 1)[1].strip()
    return request.query_params.get("access_token") or request.cookies.get("access_token")


async def _authorize_artifact(request: Request, bucket: Bucket, key: str) -> None:
    artifact_token = request.query_params.get("artifact_token")
    if artifact_token:
        try:
            payload = pyjwt.decode(artifact_token, JWT_SECRET, algorithms=[JWT_ALGORITHM])
        except pyjwt.PyJWTError:
            raise HTTPException(401, "Invalid artifact token")
        if (
            payload.get("typ") != "artifact"
            or payload.get("bucket") != bucket
            or payload.get("key") != key
        ):
            raise HTTPException(403, "Artifact token does not match this object")
        return

    access_token = _extract_access_token(request)
    if not access_token:
        raise HTTPException(401, "Missing artifact token")
    try:
        payload = decode_token(access_token)
    except pyjwt.PyJWTError:
        raise HTTPException(401, "Invalid access token")
    if payload.get("typ") != "access":
        raise HTTPException(401, "Access token required")
    if await is_revoked(payload.get("jti")):
        raise HTTPException(401, "Token revoked")


def _range_response(data: bytes, key: str, range_header: str | None) -> FastAPIResponse:
    media_type = mimetypes.guess_type(key)[0] or "application/octet-stream"
    headers = _cors_headers()
    total = len(data)

    if range_header and range_header.startswith("bytes="):
        start_s, _, end_s = range_header[len("bytes=") :].partition("-")
        try:
            start = int(start_s) if start_s else 0
            end = int(end_s) if end_s else total - 1
        except ValueError:
            raise HTTPException(416, "Invalid Range header")
        if start < 0 or end < start or start >= total:
            raise HTTPException(416, "Requested range not satisfiable")
        end = min(end, total - 1)
        headers["Content-Range"] = f"bytes {start}-{end}/{total}"
        headers["Content-Length"] = str(end - start + 1)
        return FastAPIResponse(
            content=data[start : end + 1],
            status_code=206,
            media_type=media_type,
            headers=headers,
        )

    headers["Content-Length"] = str(total)
    return FastAPIResponse(content=data, media_type=media_type, headers=headers)


async def _serve(request: Request, bucket: Bucket, key: str) -> FastAPIResponse:
    key = _safe_key(key)
    await _authorize_artifact(request, bucket, key)
    data = fetch_bytes(bucket, key)
    return _range_response(data, key, request.headers.get("range"))


@router.options("/pics/{key:path}", include_in_schema=False)
@router.options("/results/{key:path}", include_in_schema=False)
async def artifact_options(key: str) -> Response:
    return Response(status_code=204, headers=_cors_headers())


@router.get("/pics/{key:path}", include_in_schema=False)
async def get_pic_artifact(key: str, request: Request) -> FastAPIResponse:
    return await _serve(request, "pic", key)


@router.get("/results/{key:path}", include_in_schema=False)
async def get_result_artifact(key: str, request: Request) -> FastAPIResponse:
    return await _serve(request, "results", key)
